spring.application.name=PRODUCT-SERVICE
server.port=8081

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=PRODUCT_SERVICE
spring.datasource.password=Bakka@1234567
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


#Logging Pattern console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [CorrelationID-%X{correlationId}] [TraceID-%X{trace_id}] [SpanID-%X{span_id}] %-5level %logger{36} - %msg%n
# LOGGING
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===== OpenTelemetry =====

otel.service.name=product-service
## ------------------------if protocal is otlp then port is 4317
#otel.traces.exporter=otlp
## ------------------------if protocal is http/protobuf then port is 4318
otel.traces.exporter=otlp
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.endpoint=http://localhost:4318
otel.metrics.exporter=none
otel.logs.exporter=none




